### ISSUE TITLE
CSS improvements for code samples on the blog

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/sagan#1010]
The border around code blocks looks a bit heavy due to the dark black border and lack of padding. It currently looks like this:

![Bildschirmfoto 2020-12-15 um 13 21 48](https://user-images.githubusercontent.com/128577/102214438-8dee6100-3ed8-11eb-8e78-8ff38fa76a36.png)

Changing the CSS to this:

```css
pre.prettyprint {
    padding: 1em 1.1em;
    border: 1px solid #ddd;
}
```

makes it look like this:

![Bildschirmfoto 2020-12-15 um 13 19 21](https://user-images.githubusercontent.com/128577/102214492-a52d4e80-3ed8-11eb-8936-2482749b4449.png)

which I think is less obtrusive and more pleasing to the eye.
