### ISSUE TITLE
Replace github team id by org+team name

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#325]
Finding a team id, given a team name, is not straightforward and requires manual calls to GitHub's API (or is there a better way?).

Currently, a user has to:
1. Generate a new token using https://github.com/settings/tokens/new
2. Use that token to issue: `curl https://api.github.com/user/teams -u $TOKEN:x-oauth-basic`
3. Find the team id in the list of teams

We could replace, in the current configuration:

```
github:
  team:
    id: ${GITHUB_TEAM_ID:1234}
```

By

```
github:
  org:
    name: ${GITHUB_ORG_NAME:spring-io}
  team:
    name: ${GITHUB_TEAM_NAME:spring-team}
```

The downsides, this requires:
- more env variables to be declared
- an additional API call to be made by Sagan to find the team id by itself
